function startMission(id){const m=MISSIONS.find(x=>x.id===id);if(!m)return;beginQuiz(m.ids.map(questionById),{source:m.id,bonus:m.bonus,title:m.title})}
function startUnit(u){beginQuiz(shuffle(QUESTIONS.filter(q=>q.u===Number(u))).slice(0,6),{source:`unit-${u}`,bonus:30,title:`Unidad ${u}`})}
function startAdaptive(){beginQuiz(adaptiveQuestions(5),{source:"adaptive",bonus:35,title:"Älykäs kertaus"})}
function beginQuiz(items,meta){session={items,index:0,correct:0,earned:0,...meta};showScreen("quiz");renderQuestion()}
function renderQuestion(){const q=session.items[session.index];byId("quizCounter").textContent=`${session.index+1} / ${session.items.length}`;byId("quizProgress").style.width=`${session.index/session.items.length*100}%`;byId("quizTopic").textContent=`${q.topic.toUpperCase()} · UNIDAD ${q.u}`;byId("quizPrompt").textContent=q.prompt;byId("listenBtn").onclick=()=>speak(q.speak);byId("choices").innerHTML=shuffle(q.choices).map(c=>`<button class="choice" data-answer="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join("");byId("feedback").innerHTML='<span>💡</span><p>Virhe ei vie kolikoita. Vaikea asia palaa myöhemmin uudelleen.</p>'}
function answerQuestion(choiceEl){if(!session||choiceEl.dataset.locked)return;const q=session.items[session.index],value=choiceEl.dataset.answer;qsa(".choice").forEach(el=>{el.dataset.locked="1";if(el.dataset.answer===q.answer)el.classList.add("good")});if(value===q.answer){session.correct++;session.earned+=12;state.xp+=10;state.mastery[q.id]=clamp((state.mastery[q.id]||0)+1,0,5);byId("feedback").innerHTML='<span>✅</span><p><strong>¡Muy bien!</strong> Oikein. Saat tästä +12 🪙.</p>';coinBurst(choiceEl,true)}else{choiceEl.classList.add("bad");state.mastery[q.id]=clamp((state.mastery[q.id]||0)-1,0,5);byId("feedback").innerHTML=`<span>🌱</span><p><b>Casi — melkein.</b><br>Oikea vastaus: <strong>${escapeHtml(q.answer)}</strong></p>`}const btn=document.createElement("button");btn.className="btn primary next-btn";btn.textContent=session.index===session.items.length-1?"Katso tulos":"Seuraava →";btn.onclick=nextQuestion;byId("feedback").appendChild(btn);localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function nextQuestion(){session.index++;if(session.index<session.items.length){renderQuestion();return}finishQuiz()}
function finishQuiz(){const accuracyBonus=Math.round(session.correct/session.items.length*20),totalCoins=session.earned+session.bonus+accuracyBonus,trustGain=Math.max(1,session.correct);state.coins+=totalCoins;state.trust=clamp(state.trust+trustGain,0,100);state.skill=clamp(state.skill+Math.max(1,Math.round(session.correct/2)),0,100);if(MISSIONS.some(m=>m.id===session.source))state.done[session.source]=true;saveState();byId("resultText").textContent=`${session.correct}/${session.items.length} oikein · ${session.title}`;byId("resultCoins").textContent=`+${totalCoins}`;byId("resultXp").textContent=`+${session.items.length*10}`;byId("resultTrust").textContent=`+${trustGain}`;showScreen("result");confetti()}
function coinBurst(sourceEl,small=true){const r=sourceEl.getBoundingClientRect?sourceEl.getBoundingClientRect():{left:innerWidth/2,top:innerHeight/2,width:0,height:0},count=small?3:7;for(let i=0;i<count;i++){const c=document.createElement("div");c.className="coin-fly";c.textContent="🪙";c.style.left=`${r.left+r.width/2+(Math.random()*50-25)}px`;c.style.top=`${r.top+Math.random()*25}px`;c.style.animationDelay=`${i*.05}s`;document.body.appendChild(c);setTimeout(()=>c.remove(),1100)}}
function confetti(){const colors=["#d6a13c","#6d9a73","#a66b57","#e4c86a","#8aa0c5"];for(let i=0;i<32;i++){const e=document.createElement("i");e.className="confetti";e.style.left=`${Math.random()*100}vw`;e.style.top=`${-20-Math.random()*80}px`;e.style.background=colors[i%colors.length];e.style.animationDelay=`${Math.random()*.5}s`;e.style.animationDuration=`${1+Math.random()*.8}s`;document.body.appendChild(e);setTimeout(()=>e.remove(),2300)}}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.addEventListener("click",e=>{const nav=e.target.closest("[data-nav]");if(nav){showScreen(nav.dataset.nav);return}const mission=e.target.closest("[data-start-mission]");if(mission){startMission(mission.dataset.startMission);return}const buy=e.target.closest("[data-buy]");if(buy){buyItem(buy.dataset.buy,buy);return}const care=e.target.closest("[data-care]");if(care){careAction(care.dataset.care);return}const unit=e.target.closest("[data-unit]");if(unit){startUnit(unit.dataset.unit);return}const choice=e.target.closest(".choice");if(choice)answerQuestion(choice)});
byId("dailyBtn").addEventListener("click",startAdaptive);byId("adaptiveBtn").addEventListener("click",startAdaptive);byId("careBtn").addEventListener("click",()=>showScreen("care"));byId("quizBack").addEventListener("click",()=>showScreen("play"));
createDust();renderAll();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=0.2.0").catch(()=>{}));