let state = loadState();
let session = null;
let lastScreen = "home";
const qs=(s,root=document)=>root.querySelector(s),qsa=(s,root=document)=>[...root.querySelectorAll(s)],byId=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),questionById=id=>QUESTIONS.find(q=>q.id===id),shuffle=arr=>[...arr].sort(()=>Math.random()-.5);
function loadState(){try{const old=JSON.parse(localStorage.getItem(STORE_KEY)||"{}");return {...DEFAULT_STATE,...old,owned:Array.isArray(old.owned)?old.owned:[...DEFAULT_STATE.owned],mastery:old.mastery||{},done:old.done||{},careUses:{...DEFAULT_STATE.careUses,...(old.careUses||{})}}}catch{return structuredClone(DEFAULT_STATE)}}
function saveState(){localStorage.setItem(STORE_KEY,JSON.stringify(state));renderAll()}
function toast(message){const el=byId("toast");el.textContent=message;el.classList.add("is-on");clearTimeout(toast._t);toast._t=setTimeout(()=>el.classList.remove("is-on"),1700)}
function showScreen(name){lastScreen=name;qsa(".screen").forEach(el=>el.classList.toggle("is-active",el.id===`screen-${name}`));qsa("[data-nav]").forEach(el=>{if(el.closest(".bottom-nav"))el.classList.toggle("is-active",el.dataset.nav===name)});byId("bottomNav").classList.toggle("is-hidden",["quiz","result"].includes(name));window.scrollTo({top:0,behavior:"smooth"})}
function speak(text){if(!("speechSynthesis" in window))return toast("Tämän selaimen puhesynteesi ei ole käytettävissä.");const u=new SpeechSynthesisUtterance(text);u.lang="es-ES";u.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(u)}
function createDust(){const root=byId("dust");if(!root||root.childElementCount)return;for(let i=0;i<15;i++){const p=document.createElement("i");p.style.left=`${8+Math.random()*84}%`;p.style.top=`${38+Math.random()*55}%`;p.style.animationDelay=`${-Math.random()*8}s`;p.style.animationDuration=`${6+Math.random()*6}s`;p.style.opacity=`${.25+Math.random()*.6}`;root.appendChild(p)}}
function renderAll(){byId("coins").textContent=state.coins;byId("shopCoins").textContent=state.coins;byId("xp").textContent=state.xp;byId("learned").textContent=Object.values(state.mastery).filter(v=>v>=4).length;byId("trustText").textContent=state.trust;byId("careText").textContent=state.care;byId("skillText").textContent=state.skill;byId("trustBar").style.width=`${state.trust}%`;byId("careBar").style.width=`${state.care}%`;byId("skillBar").style.width=`${state.skill}%`;renderToday();renderMissions();renderShop();renderChapters()}
function renderToday(){const next=MISSIONS.find(m=>!state.done[m.id])||MISSIONS[0];byId("todayMission").innerHTML=`<div class="mission-card"><div class="mission-icon">${next.icon}</div><div><b>${next.title}</b><small>Unidad ${next.u} · ${next.desc}</small></div><button class="btn primary" data-start-mission="${next.id}">Aloita</button></div>`}
function renderMissions(){byId("missionList").innerHTML=MISSIONS.map(m=>`<article class="mission-row ${state.done[m.id]?"done":""}"><div class="stamp">${state.done[m.id]?"✅":m.icon}</div><div><h3>${m.title}</h3><p>Unidad ${m.u} · ${m.desc}</p></div><button class="btn ${state.done[m.id]?"soft":"primary"}" data-start-mission="${m.id}">${state.done[m.id]?"Uudestaan":"Aloita"}</button></article>`).join("")}
function renderShop(){byId("shopGrid").innerHTML=SHOP_ITEMS.map(item=>{const owned=state.owned.includes(item.id);return `<article class="shop-item"><div><div class="shop-item-icon">${item.icon}</div><h3>${item.name}</h3><small>${item.desc}</small></div><div class="price-row">${owned?'<span class="owned">✓ Omistat</span>':`<span class="price">🪙 ${item.price}</span><button class="btn soft" data-buy="${item.id}">Osta</button>`}</div></article>`}).join("")}
function renderChapters(){byId("chapterGrid").innerHTML=CHAPTERS.map(c=>`<button class="chapter-card" ${c.open?`data-unit="${c.u}"`:"disabled"}><div class="chapter-number">${c.icon}</div><span class="eyebrow">UNIDAD ${c.u}</span><h3>${c.title}</h3><p>${c.desc}</p><small>${c.open?"Harjoittele nyt →":"Tulossa myöhemmin"}</small></button>`).join("")}
function buyItem(id,sourceEl){const item=SHOP_ITEMS.find(x=>x.id===id);if(!item||state.owned.includes(id))return;if(state.coins<item.price)return toast("Kolikot eivät vielä riitä tähän varusteeseen.");state.coins-=item.price;state.owned.push(id);state.trust=clamp(state.trust+3,0,100);saveState();coinBurst(sourceEl||document.body,false);toast(`${item.name} ostettu Lunalle!`)}
function careAction(type){const messages={brush:"Luna rentoutuu harjauksen aikana. ¡Muy bien!",feed:"Luna ottaa porkkanan varovasti kädestäsi. La zanahoria.",water:"Raikas vesi tekee hyvää. El agua."};state.careUses[type]=(state.careUses[type]||0)+1;if(type==="brush"){state.care=clamp(state.care+4,0,100);state.trust=clamp(state.trust+1,0,100);replayAnim("brushSweep","animate-brush")}else if(type==="feed"){state.trust=clamp(state.trust+2,0,100);replayAnim("feedFloat","animate-feed");replayAnim("heartPop","animate-heart");speak("la zanahoria")}else{state.care=clamp(state.care+2,0,100);replayAnim("heartPop","animate-heart");speak("el agua")}byId("careMessage").textContent=messages[type];saveState()}
function replayAnim(id,cls){const el=byId(id);el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls)}
function adaptiveQuestions(count=5){return [...QUESTIONS].map(q=>({q,score:(state.mastery[q.id]||0)+Math.random()*1.2})).sort((a,b)=>a.score-b.score).slice(0,count).map(x=>x.q)}
